const {chromium}=require('playwright');const path=require('node:path');const fs=require('node:fs');const assert=require('node:assert/strict');
const base=process.env.PLATFORM_TEST_ORIGIN||'http://127.0.0.1:5700';
if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(base))throw new Error('Local tests only');
(async()=>{const browser=await chromium.launch({headless:true});const dir=path.resolve('platform/test-results');fs.mkdirSync(dir,{recursive:true});try{
 for(const width of [320,360,375,390,430,500,768,1024,1440]){console.log(`Checking ${width}px`);
  const page=await browser.newPage({viewport:{width,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/');await page.getByRole('heading',{name:'Lumiq',exact:true}).waitFor();await page.screenshot({path:path.join(dir,`home-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.goto(base+'/pricing');await page.getByRole('heading',{name:'Plans for your people.'}).waitFor();await page.screenshot({path:path.join(dir,`pricing-${width}.png`),fullPage:true});await page.goto(base+'/sample-workspace');await page.getByRole('heading',{name:'My events',exact:true}).waitFor();await page.screenshot({path:path.join(dir,`workspace-${width}.png`),fullPage:true});
  const menu=page.locator('.mobile-workspace-nav');if(width<=760){assert.equal(await menu.isVisible(),true);assert.equal(await menu.evaluate(element=>element.open),false);assert.equal(await page.locator('.desktop-workspace-nav').isVisible(),false);assert.equal(await page.locator('.app-topbar .actions').isVisible(),false);await menu.locator('summary').click();assert.equal(await menu.getByRole('link',{name:'Account'}).isVisible(),true);assert.equal(await menu.getByRole('button',{name:'Switch color theme'}).isVisible(),true);assert.equal(await menu.getByRole('button',{name:'Sign out'}).isVisible(),true);assert.equal(await menu.locator('[data-language]').count(),1);await page.screenshot({path:path.join(dir,`mobile-menu-${width}.png`),fullPage:true});await page.locator('#main').click({position:{x:5,y:5}});assert.equal(await menu.evaluate(element=>element.open),false);await menu.locator('summary').click();await page.keyboard.press('Escape');assert.equal(await menu.evaluate(element=>element.open),false);await menu.locator('summary').click();await menu.getByRole('link',{name:'Account'}).click();await page.getByRole('heading',{name:'Account',exact:true}).waitFor();await page.goto(base+'/sample-workspace');await page.getByRole('heading',{name:'My events',exact:true}).waitFor();}else assert.equal(await menu.isVisible(),false);
  const row=page.locator('.event-row').filter({hasText:'Sophie & Oliver'});assert.equal(await row.evaluate(element=>element.tagName),'A');assert.equal(await row.locator('.row-open').count(),0);await page.getByRole('button',{name:'Create event',exact:true}).click();await page.locator('#event-form').waitFor();assert.equal(await page.locator('#cover option[value=""]').count(),0);assert.equal(await page.locator('#cover').inputValue(),'/assets/garden-gathering.webp');const dialogLayout=await page.locator('#event-form').evaluate(form=>{const dialog=form.closest('dialog'),start=form.querySelector('[name="start"]').getBoundingClientRect(),end=form.querySelector('[name="end"]').getBoundingClientRect();return {pageOverflow:document.documentElement.scrollWidth>innerWidth,dialogOverflow:dialog.scrollWidth>dialog.clientWidth+1,endBelowStart:end.top>=start.bottom-1,endWithin: end.right<=dialog.getBoundingClientRect().right+1};});assert.equal(dialogLayout.pageOverflow,false);assert.equal(dialogLayout.dialogOverflow,false);assert.equal(dialogLayout.endWithin,true);if(width<=640)assert.equal(dialogLayout.endBelowStart,true);await page.screenshot({path:path.join(dir,`create-${width}.png`),fullPage:true});await page.getByRole('button',{name:'Close dialog'}).click();await page.waitForFunction(()=>document.activeElement?.id==='create-event');
  await row.locator('h3').click();await page.locator('.gallery-grid img').first().waitFor();const galleryLayout=await page.locator('.toolbar').evaluate(toolbar=>({overflow:toolbar.scrollWidth>toolbar.clientWidth+1,widths:[...toolbar.querySelectorAll('.field')].map(field=>field.getBoundingClientRect().width),actions:[...toolbar.querySelectorAll('button')].every(button=>{const r=button.getBoundingClientRect(),p=toolbar.getBoundingClientRect();return r.left>=p.left-1&&r.right<=p.right+1})}));assert.equal(galleryLayout.overflow,false);assert.equal(galleryLayout.actions,true);if(width<=640)assert.ok(Math.max(...galleryLayout.widths)-Math.min(...galleryLayout.widths)<2);const tabLayout=await page.locator('.tabs').evaluate(tabs=>({overflow:tabs.scrollWidth>tabs.clientWidth+1,items:[...tabs.children].map(item=>item.getBoundingClientRect())}));if(width<=640){assert.equal(tabLayout.overflow,false);assert.ok(tabLayout.items.every(item=>item.right<=width-10))}await page.screenshot({path:path.join(dir,`gallery-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.goto(base+'/demo');await page.getByRole('heading',{name:'The summer gathering'}).waitFor();await page.screenshot({path:path.join(dir,`guest-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);await page.close();
 }
  const productionPreview=await browser.newPage(),localDemoRequests=[];await productionPreview.route('**/api/config',async route=>{const response=await route.fetch(),config=await response.json();await route.fulfill({response,json:{...config,local:false}});});productionPreview.on('request',request=>{if(new URL(request.url()).pathname==='/api/local/demo')localDemoRequests.push(request.url());});await productionPreview.goto(base+'/demo');await productionPreview.waitForURL('**/features');await productionPreview.getByRole('heading',{name:/One event\./}).waitFor();assert.deepEqual(localDemoRequests,[]);await productionPreview.close();
  const expiredConfirmation=await browser.newPage(),consumeRequests=[];expiredConfirmation.on('request',request=>{if(new URL(request.url()).pathname==='/api/auth/consume')consumeRequests.push(request.url());});await expiredConfirmation.goto(base+'/auth/verify?error=access_denied&error_code=otp_expired&error_description=fixture-secret');await expiredConfirmation.getByRole('heading',{name:'Email link unavailable'}).waitFor();assert.match(await expiredConfirmation.locator('#main').innerText(),/already been used or has expired/i);assert.equal(await expiredConfirmation.getByRole('button',{name:'Verify email'}).count(),0);assert.equal(await expiredConfirmation.locator('#main').getByRole('link',{name:'Sign in'}).getAttribute('href'),'/login');assert.deepEqual(consumeRequests,[]);assert.equal(new URL(expiredConfirmation.url()).search,'');await expiredConfirmation.close();
  console.log('Browser checks passed at 320px, 360px, 375px, 390px, 430px, 500px, 768px, 1024px and 1440px, including the production /demo redirect. Screenshots: platform/test-results');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
