const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const sharp=require('sharp');
const base=process.env.PLATFORM_TEST_ORIGIN||'http://127.0.0.1:5700';
if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(base))throw new Error('Local tests only');
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Europe/Riga'}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await context.request.post(base+'/api/local/demo-session',{headers:{Origin:base}});
  const created=await context.request.post(base+'/api/events',{headers:{Origin:base},data:{name:'Our summer gathering',start:new Date(Date.now()-3600000).toISOString().slice(0,16),end:new Date(Date.now()+3600000).toISOString().slice(0,16),time_zone:'UTC',cover:'/assets/garden-gathering.webp'}});
  const event=await created.json();assert(event.id);
  await page.goto(`${base}/app/events/${event.id}?tab=design`);await page.locator('#guest-canvas').waitFor();await page.waitForFunction(()=>document.querySelector('#guest-canvas')?.dataset.editorReady==='true');assert.equal(await page.locator('#camera-canvas').evaluate(el=>getComputedStyle(el.parentElement).display),'none','The hidden camera Fabric wrapper must not cover the welcome editor on initial load');assert.equal(await page.locator('#guest-canvas').evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height*.2)===el.parentElement.querySelector('.upper-canvas')}),true,'The welcome canvas must receive pointer events before switching screens');
  await page.locator('#guest-add-text').click();await page.keyboard.type('Welcome friends');await page.locator('#guest-size').fill('54');await page.locator('#guest-color').fill('#e6d240');await page.locator('#guest-font').selectOption('montserrat');await page.locator('#guest-bold').click();
  await page.locator('#guest-draw').click();assert.equal(await page.locator('#guest-draw').getAttribute('aria-pressed'),'true');await page.locator('#guest-draw').click();assert.equal(await page.locator('#guest-draw').getAttribute('aria-pressed'),'false','The drawing button should toggle drawing off');await page.locator('#guest-draw').click();await page.locator('#guest-add-emoji').click();assert((await page.locator('#guest-emoji-picker [data-emoji]').count())>=60,'Emoji palette should offer a broad selection');await page.locator('#guest-emoji-picker-search').fill('balloon');await page.locator('#guest-emoji-picker [data-emoji]:visible').first().click();assert.equal(await page.locator('#guest-draw').getAttribute('aria-pressed'),'false','Adding an emoji should leave drawing mode so it can be selected and moved');await page.locator('#guest-undo').click();await page.locator('#guest-redo').click();
  await page.locator('[name=showTitle]').evaluate(el=>{el.checked=false;el.dispatchEvent(new Event('change',{bubbles:true}));});await page.locator('[name=showDate]').evaluate(el=>{el.checked=false;el.dispatchEvent(new Event('change',{bubbles:true}));});await page.locator('[name=showTitle]').evaluate(el=>{el.checked=true;el.dispatchEvent(new Event('change',{bubbles:true}));});
   assert.equal(await page.locator('#design-form [name=title]:visible,#design-form [name=subtitle]:visible,#design-form [name=button]:visible,#design-form [name=chooseButton]:visible').count(),0,'Canvas text and button labels should not need side input fields');assert.equal(await page.locator('.designer-section:has-text("Page text")').count(),0,'Redundant Page text controls should be removed');assert.equal(await page.locator('#design-form input[type=color]').count(),1,'A single color picker should style all selected elements');await page.locator('[data-button-key="joinButton"]').click();await page.locator('#guest-color').fill('#e6d240');assert.equal(await page.locator('[data-button-key="joinButton"]').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 255, 255)','Text color must not change button background');await page.locator('[data-button-color-target="fill"]').click();await page.locator('#guest-color').fill('#173e32');assert.equal(await page.locator('[data-button-key="joinButton"]').evaluate(el=>getComputedStyle(el).color),'rgb(230, 210, 64)','Button background color must not change text color');await page.locator('[data-button-color-target="text"]').click();await page.locator('#guest-color').fill('#173e32');await page.locator('[data-button-color-target="fill"]').click();await page.locator('#guest-color').fill('#ffffff');await page.locator('#design-form [name=title]').evaluate(el=>{el.value='Every little moment';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#design-form [name=subtitle]').evaluate(el=>{el.value='A summer evening with our favorite people.';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('.guest-canvas-stage .canvas-container:visible .upper-canvas').first().click({position:{x:195,y:150},force:true});await page.locator('#guest-delete').click();assert.equal(await page.locator('[name=showTitle]').isChecked(),false,'Deleting the cover title must turn off title rendering');
  await page.locator('#cover-file').setInputFiles({name:'guest-cover.png',mimeType:'image/png',buffer:await sharp({create:{width:600,height:1000,channels:3,background:'#397f65'}}).png().toBuffer()});
  await page.screenshot({path:'platform/test-results/designer-desktop.png',fullPage:true});
  const guestSave=page.waitForResponse(response=>response.url().includes('/api/events/')&&response.request().method()==='PATCH'),coverSave=page.waitForResponse(response=>response.url().endsWith('/cover')&&response.request().method()==='POST');await page.getByRole('button',{name:'Save guest page',exact:true}).click();assert.equal((await guestSave).status(),200);assert.equal((await coverSave).status(),200);
  let saved=await(await context.request.get(`${base}/api/events/${event.id}`)).json();assert.equal(saved.appearance.title,'Every little moment');assert.equal(saved.appearance.showTitle,false);assert(!saved.appearance.guest_design.objects.some(object=>object.lumiqRole==='guest-title'));assert(saved.appearance.guest_design.lumiqHiddenRoles.includes('guest-title'));assert(!saved.appearance.guest_design.objects.some(object=>object.lumiqRole==='guest-date'));assert(saved.appearance.guest_design.objects.some(object=>object.lumiqRole==='background'));assert(saved.appearance.guest_design.objects.some(object=>object.text==='Welcome friends'));assert(saved.appearance.guest_design.objects.some(object=>object.text==='🎈'));assert(saved.appearance.cover_base_key);assert(saved.appearance.cover.includes('design=1'));
  const source=await context.request.get(`${base}/api/covers/${event.id}?source=1`);assert.equal(source.status(),200);assert.equal(source.headers()['content-type'],'image/webp');
  await page.setViewportSize({width:390,height:844});await page.goto(`${base}/app/events/${event.id}?tab=design`);await page.locator('#guest-canvas').waitFor();await page.waitForTimeout(200);const dimensions=await page.evaluate(()=>{const r=document.querySelector('.guest-canvas-stage').getBoundingClientRect();return {width:innerWidth,document:document.documentElement.scrollWidth,stage:r.width,ratio:r.width/r.height};});assert.equal(dimensions.document,dimensions.width);assert(dimensions.stage<=dimensions.width);assert(Math.abs(dimensions.ratio-390/760)<.01,'Guest canvas preview must retain its design aspect ratio');await page.screenshot({path:'platform/test-results/designer-mobile.png',fullPage:true});
  await context.request.post(`${base}/api/events/${event.id}/action`,{headers:{Origin:base},data:{action:'publish'}});
  await page.goto(`${base}/event/${event.slug}`);await page.locator('.guest-title h1').waitFor({state:'detached'});await page.getByLabel('Your name').fill('Guest Test');await page.getByRole('button',{name:'Join the gathering'}).click();await page.getByRole('button',{name:'Take a photo'}).waitFor();assert((await page.locator('.guest-image-frame img').getAttribute('src')).includes('design=1'));
  await page.goto(`${base}/app`);const eventRow=page.locator('.event-row').filter({hasText:event.name});await eventRow.waitFor();assert.equal(await eventRow.locator('img').getAttribute('src'),saved.appearance.cover,'The event list thumbnail must use this event\'s saved welcome design cover');assert.equal(await eventRow.locator('img').evaluate(image=>image.complete&&image.naturalWidth>0),true,'The saved welcome design cover must load as the event thumbnail');
  await page.goto(`${base}/app/events/${event.id}?tab=gallery`);await page.locator('#qr').waitFor();const editorDialog=page.locator('#dialog');assert.equal(await editorDialog.isVisible(),false,'The QR editor must not render under the event gallery before the QR action is selected');await page.locator('#qr').click();await page.waitForFunction(()=>{const dialog=document.querySelector('#dialog');return dialog?.open&&dialog.querySelector('#qr-canvas');});assert.equal(await editorDialog.evaluate(dialog=>dialog.matches(':modal')),true,'The QR editor should open as a modal');const toolHeights=await page.evaluate(()=>['#editor-add-text','#editor-add-emoji'].map(selector=>document.querySelector(selector).getBoundingClientRect().height));assert.equal(toolHeights[0],toolHeights[1],'QR and Emoji controls should have matching heights');await editorDialog.locator('.dialog-head button').click();await page.waitForFunction(()=>!document.querySelector('#dialog')?.open);assert.equal(await editorDialog.evaluate(dialog=>getComputedStyle(dialog).display),'none','Closing the QR editor must remove it from page layout');
  assert.deepEqual(errors,[]);await context.request.post(`${base}/api/events/${event.id}/action`,{headers:{Origin:base},data:{action:'delete',confirm:event.name}});
  console.log('Guest canvas editor passed: text/emoji layers, styling, cover upload, persisted scene, mobile layout and guest rendering.');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
