import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import {unzipSync} from 'fflate';
import {createHmac} from 'node:crypto';
import {openDatabase} from '../server/db.mjs';
import {createApp} from '../server/app.mjs';
import {storage} from '../server/storage.mjs';
import {hash,uuid} from '../server/security.mjs';
import {verifyStripe} from '../server/billing.mjs';
import {schedule} from '../server/events.mjs';
import {folder} from '../shared/plans.js';
test('full isolated customer, photo and export flow',async t=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'lumiq-test-')),db=await openDatabase({memory:true}),origin='http://127.0.0.1:5799';
 const app=await createApp({db,files:storage({root}),origin});let cookie='',e,g,mid;
 const call=async(p,body,method=body?'POST':'GET',headers={})=>{const r=await app.handle(new Request(origin+'/api'+p,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,...headers},...(body?{body:JSON.stringify(body)}:{})}));return {r,data:await r.json()};};
 try{
 await t.test('automatic clocks and readable names with unique IDs',()=>{assert.equal(schedule({start:'2026-09-13T18:00',end:'2026-09-13T23:00',time_zone:'America/New_York'}).starts_at,'2026-09-13T22:00:00.000Z');assert.throws(()=>schedule({start:'2026-03-29T03:30',end:'2026-03-29T05:00',time_zone:'Europe/Riga'}));assert.match(folder('Sophie & Oliver',uuid()),/^sophie-oliver--/);});
 await t.test('register, verify once, login and session',async()=>{assert.equal((await call('/auth/register',{name:'Owner',email:'owner@example.test',password:'Test-password-123!'})).r.status,200);assert.equal((await call('/auth/login',{email:'owner@example.test',password:'Test-password-123!'})).r.status,403);const inbox=await call('/local/inbox'),token=new URL(inbox.data[0].body).searchParams.get('token');assert.equal((await call('/auth/consume',{token})).r.status,200);assert.equal((await call('/auth/consume',{token})).r.status,400);const login=await call('/auth/login',{email:'owner@example.test',password:'Test-password-123!'});cookie=login.r.headers.get('set-cookie').split(';')[0];assert((await call('/auth/session')).data.user);});
 await t.test('draft preview and editable QR designs are safe and readable',async()=>{
  const start=new Date(Date.now()-3600000).toISOString().slice(0,16),end=new Date(Date.now()+3600000).toISOString().slice(0,16);
  e=(await call('/events',{name:'Integration party',start,end,time_zone:'UTC',cover:'/assets/garden-gathering.webp'})).data;
  assert(e.id);
  assert.match(e.storage_prefix,/^owner-[0-9a-f]{6}\/events\/integration-party-[0-9a-f]{6}$/);
  const coverChange=await call(`/events/${e.id}`,{name:e.name,description:e.description,start,end,time_zone:'UTC',cover:'/assets/party.webp'},'PATCH');
  assert.equal(coverChange.data.appearance.cover,'/assets/party.webp');
  e=coverChange.data;
  const appearanceOnly=await call(`/events/${e.id}`,{name:e.name,description:e.description,title:'Integration design'},'PATCH');
  assert.equal(appearanceOnly.r.status,200);
  assert.equal(appearanceOnly.data.starts_at,e.starts_at);
  assert.equal(appearanceOnly.data.ends_at,e.ends_at);
  assert.equal((await call(`/events/${e.id}`,{name:e.name,description:e.description,start},'PATCH')).r.status,400);
  e=appearanceOnly.data;
  const preview=(await call(`/events/${e.id}/preview`,{})).data,previewUrl=new URL(preview.url),secret=previewUrl.searchParams.get('preview');
  assert.equal(preview.expires_in,900);
  const page=await call(`/guest/${e.slug}?preview=${encodeURIComponent(secret)}`);
  assert.equal(page.r.status,200);
  assert.equal(page.data.preview,true);
  assert.equal(page.data.state,'preview');
  assert.equal((await call(`/guest/${e.slug}/join?preview=${encodeURIComponent(secret)}`,{name:'Blocked'})).r.status,403);
  for(const template of ['garden','vintage','celebration','modern']){
   const response=await app.handle(new Request(`${origin}/api/events/${e.id}/qr?format=table&template=${template}`,{headers:{Origin:origin,Cookie:cookie}}));
   assert.equal(response.status,200);
   assert.equal(response.headers.get('content-type'),'image/svg+xml');
   assert.equal(response.headers.get('content-disposition'),null);
   const poster=await response.text();
   assert.match(poster,/width="210mm" height="148mm" viewBox="0 0 2480 1748"/);
   assert.match(poster,/<path stroke="#000" d="M/);
   assert.match(poster,/LUMIQ/);
   assert(poster.length>1000);
  }
  const saved=(await call(`/events/${e.id}/qr-layout`,{template:'modern',font:'montserrat',titleSize:999,textX:-5,textY:.2,qrX:.72,qrY:.65,qrScale:1.18})).data;
  assert.deepEqual(saved,{template:'modern',font:'montserrat',titleSize:104,textX:.18,textY:.2,qrX:.72,qrY:.65,qrScale:1.18});
  assert.deepEqual((await call(`/events/${e.id}`)).data.appearance.qr_layout,saved);
  const download=await app.handle(new Request(`${origin}/api/events/${e.id}/qr?format=table&download=1`,{headers:{Origin:origin,Cookie:cookie}}));
  assert.match(download.headers.get('content-disposition'),/^attachment; filename="modern-design-/);
  const standalone=await app.handle(new Request(`${origin}/api/events/${e.id}/qr?format=qr`,{headers:{Origin:origin,Cookie:cookie}}));
  assert.equal(standalone.status,200);
  assert.equal(standalone.headers.get('content-type'),'image/svg+xml');
  assert.match(await standalone.text(),/viewBox="0 0 \d+ \d+"/);
  const unsupported=await app.handle(new Request(`${origin}/api/events/${e.id}/qr?format=a5`,{headers:{Origin:origin,Cookie:cookie}}));
  assert.equal(unsupported.status,400);
  const background=await sharp({create:{width:600,height:900,channels:3,background:'#d7e7dd'}}).png().toBuffer();
  assert.equal((await call(`/events/${e.id}/qr-background`,{data:background.toString('base64')})).r.status,200);
  const custom=await app.handle(new Request(`${origin}/api/events/${e.id}/qr?format=table&template=custom`,{headers:{Origin:origin,Cookie:cookie}}));
  assert.equal(custom.status,200);
  assert.equal(custom.headers.get('content-type'),'image/webp');
  const customMetadata=await sharp(Buffer.from(await custom.arrayBuffer())).metadata();
  assert.equal(customMetadata.width,600);
  assert.equal(customMetadata.height,900);
 });
 await t.test('publish, pause and guest entry',async()=>{await db.query('update events set storage_prefix=$1 where id=$2',[`legacy/${e.id}`,e.id]);assert.equal((await call(`/events/${e.id}/action`,{action:'publish'})).r.status,200);assert.equal((await call('/admin')).r.status,403);await call(`/events/${e.id}/action`,{action:'pause'});assert.equal((await call(`/guest/${e.slug}/join`,{name:'Blocked'})).r.status,409);await call(`/events/${e.id}/action`,{action:'resume'});g=(await call(`/guest/${e.slug}/join`,{name:'Guest One'})).data;assert(g.token);});
 await t.test('video files are rejected by the guest image-conversion endpoint',async()=>{const rejected=await app.handle(new Request(`${origin}/api/guest/${e.slug}/convert`,{method:'PUT',headers:{Origin:origin,'Content-Type':'video/mp4','X-Guest-Token':g.token},body:Buffer.from('synthetic video payload')}));assert.equal(rejected.status,415);assert.match((await rejected.json()).error,/Only HEIC or HEIF photos need conversion/);});
 await t.test('file pair validation, stable retries, gallery isolation',async()=>{const photo=await sharp({create:{width:80,height:60,channels:3,background:'#397755'}}).webp().toBuffer();mid=uuid();const capturedAt=Date.parse('2026-09-24T10:15:30.000Z'),body={id:mid,name:'test.webp',captured_at:capturedAt,bytes:photo.length,thumbnail_bytes:photo.length,checksum:hash(photo),thumbnail_checksum:hash(photo)},headers={'X-Guest-Token':g.token};const r=await call(`/guest/${e.slug}/reserve`,body,'POST',headers);assert.equal(r.r.status,200);assert.match(r.data.object_key,/^owner-[0-9a-f]{6}\/events\/integration-party-[0-9a-f]{6}\/guest-one-[0-9a-f]{6}\/guest-one-20260924T101530Z-[0-9a-f]{6}\.webp$/);assert.match(r.data.thumbnail_key,/^owner-[0-9a-f]{6}\/events\/integration-party-[0-9a-f]{6}\/guest-one-[0-9a-f]{6}\/thumb\/guest-one-20260924T101530Z-[0-9a-f]{6}\.webp$/);assert.equal((await call(`/guest/${e.slug}/reserve`,body,'POST',headers)).data.object_key,r.data.object_key);assert.equal((await call(`/guest/${e.slug}/finalize`,{id:mid},'POST',headers)).r.status,409);for(const kind of ['photo','thumb'])assert.equal((await app.handle(new Request(`${origin}/api/guest/${e.slug}/content/${mid}/${kind}`,{method:'PUT',headers:{Origin:origin,...headers},body:photo}))).status,200);assert.equal((await call(`/guest/${e.slug}/finalize`,{id:mid},'POST',headers)).r.status,200);assert.equal((await call(`/guest/${e.slug}/finalize`,{id:mid},'POST',headers)).r.status,200);assert.equal((await call(`/events/${e.id}/photos`)).data.total,1);assert.equal((await app.handle(new Request(`${origin}/api/photos/${mid}/photo`))).status,403);});
 await t.test('photo asset authorization reads photo and event together',async()=>{
  const statements=[],query=db.query;db.query=async(...args)=>{statements.push(args[0]);return query(...args);};
  try{const asset=await app.handle(new Request(`${origin}/api/photos/${mid}/thumb`,{headers:{Origin:origin,Cookie:cookie}}));assert.equal(asset.status,200);assert.equal(asset.headers.get('content-type'),'image/webp');}
  finally{db.query=query;}
  assert.equal(statements.filter(statement=>/from media m join events e/i.test(statement)).length,1);
  assert.equal(statements.filter(statement=>/select \* from events where id=/i.test(statement)).length,0);
  assert.equal(statements.filter(statement=>/select \* from media where id=/i.test(statement)).length,0);
 });
 await t.test('sharing revokes access and the automatic full-gallery archive survives reload',async()=>{
  await db.query("update events set starts_at=now()-interval '2 hours',ends_at=now()-interval '1 hour' where id=$1",[e.id]);
  assert.equal((await call(`/events/${e.id}/action`,{action:'share',enabled:true,days:4})).r.status,200);
  assert.equal((await call(`/guest/${e.slug}/photos`)).data.total,1);
  const sharedAsset=await app.handle(new Request(`${origin}/api/photos/${mid}/thumb`,{headers:{Origin:origin}}));assert.equal(sharedAsset.status,200);
  await call(`/events/${e.id}/action`,{action:'share',enabled:false,days:4});assert.equal((await call(`/guest/${e.slug}/photos`)).r.status,403);assert.equal((await app.handle(new Request(`${origin}/api/photos/${mid}/thumb`,{headers:{Origin:origin}}))).status,403);
  assert.equal((await call(`/events/${e.id}/export`,{})).r.status,404,'Manual export creation is not available.');
  await app.jobs.retention();let job=(await call(`/events/${e.id}/jobs`)).data.find(item=>item.type==='export'&&item.payload.automatic);assert(job);
  const sent=[];assert.deepEqual(await app.jobs.dispatch({sendBatch:async messages=>sent.push(...messages)}),{dispatched:1});assert.equal(sent[0].body.jobId,job.id);
  assert.deepEqual(await app.jobs.dispatch({sendBatch:async messages=>sent.push(...messages)}),{dispatched:0},'A queued job is not repeatedly dispatched while its queue message is fresh.');
  await app.jobs.tick({concurrency:1,maxJobs:1,jobIds:[job.id]});
  const parts=(await db.query("select id from jobs where type='export-part' and payload->>'parent_id'=$1",[job.id])).rows;assert.equal(parts.length,1);
  const partDispatch=[];assert.deepEqual(await app.jobs.dispatch({sendBatch:async messages=>partDispatch.push(...messages)}),{dispatched:1});assert.equal(partDispatch[0].body.jobId,parts[0].id);
  await app.jobs.tick({concurrency:1,maxJobs:1,jobIds:[parts[0].id]});const ready=(await call(`/jobs/${job.id}`)).data;assert.equal(ready.status,'ready');assert.equal(ready.result.count,1);
  await db.query("update jobs set result=jsonb_set(result,'{parts,0,name}',to_jsonb($1::text)) where id=$2",['event-photos-1.zip',job.id]);
  const downloaded=await app.handle(new Request(`${origin}/api/jobs/${job.id}/download/0`,{headers:{Origin:origin,Cookie:cookie}}));assert.equal(downloaded.status,200);assert.equal(downloaded.headers.get('content-type'),'application/zip');assert.match(downloaded.headers.get('content-disposition'),/owner-integration-party-1\.zip/);
  const zip=unzipSync(Buffer.from(await downloaded.arrayBuffer()));assert(Object.keys(zip).some(name=>/^guest-one-20260924T101530Z-[0-9a-f]{6}\.webp$/i.test(name)));
  const manifest=JSON.parse(new TextDecoder().decode(zip['manifest.json']));assert.equal(manifest[0].captured,'2026-09-24T10:15:30.000Z');
  await app.jobs.retention();assert.equal((await call(`/events/${e.id}/jobs`)).data.filter(item=>item.type==='export'&&item.payload.automatic).length,1,'The scheduler must not create a replacement archive.');
 });
 await t.test('queue dispatcher emits bounded Cloudflare batches and avoids immediate duplicates',async()=>{
  const owner=(await call('/auth/session')).data.user.id;
  for(let index=0;index<205;index++)await app.jobs.queue(owner,e.id,'test-dispatch',{index});
  const sizes=[],result=await app.jobs.dispatch({sendBatch:async messages=>sizes.push(messages.length)},{limit:205});
  assert.deepEqual(result,{dispatched:205});assert.deepEqual(sizes,[100,100,5]);
  assert.deepEqual(await app.jobs.dispatch({sendBatch:async messages=>sizes.push(messages.length)},{limit:205}),{dispatched:0});
  const stale=(await db.query("select id from jobs where type='test-dispatch' order by created_at limit 1")).rows[0];await db.query("update jobs set dispatched_at=now()-interval '6 minutes' where id=$1",[stale.id]);
  assert.deepEqual(await app.jobs.dispatch({sendBatch:async messages=>sizes.push(messages.length)},{limit:205}),{dispatched:1},'A lost queue message is eventually republished from the database.');
  const failed=(await app.jobs.queue(owner,e.id,'test-dispatch',{failedSend:true})).id;
  await assert.rejects(app.jobs.dispatch({sendBatch:async()=>{throw new Error('queue unavailable');}},{limit:205}),/queue unavailable/);
  assert.equal((await db.query('select dispatched_at from jobs where id=$1',[failed])).rows[0].dispatched_at,null,'A failed Queue write must leave the DB job eligible for retry.');
  assert.deepEqual(await app.jobs.deadLetter(failed),{failed:true});assert.equal((await db.query('select status from jobs where id=$1',[failed])).rows[0].status,'failed');
  await app.jobs.retry({id:owner},failed);assert.equal((await db.query('select status from jobs where id=$1',[failed])).rows[0].status,'queued','An owner can retry a dead-lettered job.');
  await db.query("update jobs set status='ready' where type='test-dispatch'");
 });
 await t.test('verified payment simulation and deduplication',async()=>{const o=(await call('/billing/checkout',{plan:'gathering'})).data;assert.equal((await call('/billing')).data.subscription.plan,'trial');assert.equal((await call('/billing/simulate',{order:o.order,outcome:'success'})).r.status,200);assert.equal((await call('/billing/simulate',{order:o.order,outcome:'success'})).data.duplicate,true);assert.equal((await call('/billing')).data.subscription.plan,'gathering');await call('/billing/cancel',{});assert.equal((await call('/billing')).data.subscription.cancel_at_end,true);});
 await t.test('CSRF and wrong-account access denied',async()=>{
  await call('/auth/register',{name:'Other',email:'other@example.test',password:'Test-password-123!'});
  const mail=(await call('/local/inbox')).data.find(m=>m.recipient==='other@example.test');
  await call('/auth/consume',{token:new URL(mail.body).searchParams.get('token')});
  const login=await call('/auth/login',{email:'other@example.test',password:'Test-password-123!'}),outsiderCookie=login.r.headers.get('set-cookie').split(';')[0];
  assert.equal((await call(`/events/${e.id}`,null,'GET',{Cookie:outsiderCookie})).r.status,404);
  assert.equal((await app.handle(new Request(`${origin}/api/photos/${mid}/thumb`,{headers:{Origin:origin,Cookie:outsiderCookie}}))).status,403,'another organizer cannot read a photo by guessing its ID');
  const exportJob=(await db.query("select id from jobs where event_id=$1 and type='export' and status='ready' limit 1",[e.id])).rows[0];assert(exportJob,'fixture export should be ready');
  assert.equal((await app.handle(new Request(`${origin}/api/jobs/${exportJob.id}/download/0`,{headers:{Origin:origin,Cookie:outsiderCookie}}))).status,404,'another organizer cannot download an export by guessing its job ID');
  assert.equal((await app.handle(new Request(origin+`/api/events/${e.id}/action`,{method:'POST',headers:{Origin:'https://attacker.invalid',Cookie:cookie},body:JSON.stringify({action:'delete',confirm:e.name})}))).status,403);
 });
 await t.test('metadata deletion followed by object cleanup before event end',async()=>{await db.query("update events set ends_at=now()+interval '1 hour' where id=$1",[e.id]);assert.equal((await call(`/events/${e.id}/photos`,{ids:[mid]},'DELETE')).r.status,200);assert.equal((await call(`/events/${e.id}/photos`)).data.total,0);await app.jobs.tick();const m=(await db.query('select * from media where id=$1',[mid])).rows[0];await assert.rejects(app.files.get(m.object_key));});
 }finally{await db.close();await rm(root,{recursive:true,force:true});}
});
test('Stripe signature validation rejects tampering and expired replay',()=>{const body=JSON.stringify({id:'evt_test'}),secret='test-only',time=Math.floor(Date.now()/1000),sig=createHmac('sha256',secret).update(`${time}.${body}`).digest('hex');assert.equal(verifyStripe(body,`t=${time},v1=${sig}`,secret).id,'evt_test');assert.throws(()=>verifyStripe(body+' ',`t=${time},v1=${sig}`,secret));assert.throws(()=>verifyStripe(body,`t=${time-1000},v1=${sig}`,secret));});
