const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const sharp=require('sharp');
const base=process.env.PLATFORM_TEST_ORIGIN||'http://127.0.0.1:5700';
if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(base))throw Error('Local only');
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const width of [1440,1100,768,390]){
  await page.setViewportSize({width,height:1000});await page.goto(base+'/pricing');await page.locator('.plan').first().waitFor();
  const rects=await page.locator('.plan').evaluateAll(cards=>cards.map(c=>{const r=c.getBoundingClientRect(),b=c.querySelector('.button,button').getBoundingClientRect();return {top:r.top,button:b.top,height:b.height};}));
  for(const r of rects)for(const q of rects)if(Math.abs(r.top-q.top)<1){assert(Math.abs(r.button-q.button)<2,'Pricing buttons misaligned');assert(Math.abs(r.height-q.height)<2,'Pricing button heights differ');}
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(await page.locator('.site-nav').evaluate(n=>{const r=n.getBoundingClientRect(),c=n.querySelector('[data-language]').getBoundingClientRect();return c.top>=r.top&&c.bottom<=r.bottom;}),'Language control must stay inside navigation');
  await page.screenshot({path:`platform/test-results/refinement-pricing-${width}.png`,fullPage:true});
 }
 await page.setViewportSize({width:1440,height:1000});
 const a=await sharp({create:{width:300,height:900,channels:3,background:'#376559'}}).webp().toBuffer(),b=await sharp({create:{width:1000,height:300,channels:3,background:'#cc5966'}}).webp().toBuffer();
 await page.route('**/api/photos/*/photo',route=>route.fulfill({contentType:'image/webp',body:route.request().url().includes('/first/')?a:b}));
 await page.evaluate(async()=>{const {photoViewer}=await import('/photo-viewer.js');photoViewer([{id:'first',guest:'Portrait',created_at:new Date().toISOString()},{id:'second',guest:'Landscape',created_at:new Date().toISOString()}]);});
 await page.locator('.preview-image:visible').waitFor();const frame=await page.locator('.photo-stage').boundingBox(),arrow=await page.locator('.photo-next').boundingBox();
 await page.getByRole('button',{name:'Next photo',exact:true}).click();await page.locator('.preview-image[alt="Photo by Landscape"]:visible').waitFor();
 assert.deepEqual(await page.locator('.photo-stage').boundingBox(),frame);assert.deepEqual(await page.locator('.photo-next').boundingBox(),arrow);
 await page.screenshot({path:'platform/test-results/refinement-viewer-desktop.png'});
 await page.mouse.click(2,2);assert.equal(await page.locator('dialog').evaluate(d=>d.open),false);
 await page.setViewportSize({width:390,height:844});await page.evaluate(async()=>{const {photoViewer}=await import('/photo-viewer.js');photoViewer([{id:'first',guest:'Portrait',created_at:new Date().toISOString()},{id:'second',guest:'Landscape',created_at:new Date().toISOString()}]);});
 await page.locator('.photo-stage').evaluate(el=>{const a=new Touch({identifier:1,target:el,clientX:300,clientY:200}),b=new Touch({identifier:1,target:el,clientX:100,clientY:205});el.dispatchEvent(new TouchEvent('touchstart',{touches:[a]}));el.dispatchEvent(new TouchEvent('touchend',{changedTouches:[b]}));});
 await page.locator('.preview-image[alt="Photo by Landscape"]:visible').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'platform/test-results/refinement-viewer-mobile.png'});await page.keyboard.press('Escape');
 await page.goto(base+'/pricing');await page.getByRole('button',{name:'Language',exact:true}).click();await page.getByRole('listbox',{name:'Language'}).getByRole('option',{name:'LV',exact:true}).click();await page.waitForFunction(()=>document.documentElement.lang==='lv');await page.getByRole('link',{name:'Izvēlēties Gathering',exact:true}).waitFor();await page.reload();await page.getByRole('link',{name:'Izvēlēties Gathering',exact:true}).waitFor();await page.screenshot({path:'platform/test-results/refinement-pricing-lv.png',fullPage:true});await page.getByRole('button',{name:'Valoda',exact:true}).click();await page.getByRole('listbox',{name:'Valoda'}).getByRole('option',{name:'EN',exact:true}).click();await page.waitForFunction(()=>document.documentElement.lang==='en');
 await page.goto(base+'/');await page.getByRole('heading',{name:'Lumiq',exact:true}).waitFor();for(const width of [1440,390]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`platform/test-results/gathering-home-${width}.png`,fullPage:true});}
 await page.getByRole('button',{name:'Language',exact:true}).click();await page.getByRole('listbox',{name:'Language'}).getByRole('option',{name:'LV',exact:true}).click();await page.getByRole('link',{name:'Izveidot pirmo pasākumu',exact:true}).waitFor();
 assert(!(await page.locator('.hero').innerText()).includes('Your people.'));
 await page.screenshot({path:'platform/test-results/home-lv.png',fullPage:true});
 await page.goto(base+'/help');await page.getByText('Vai viesiem vajag lietotni vai kontu?',{exact:true}).waitFor();
 await page.goto(base+'/features');
 await page.getByText('Saglabā kontroli',{exact:true}).waitFor();
 await page.goto(base+'/privacy');await page.getByRole('heading',{name:'Privātuma politika',exact:true}).waitFor();await page.getByRole('heading',{name:'Kas nosaka pasākuma foto izmantošanu',exact:true}).waitFor();const privacy=await page.locator('main').innerText();for(const phrase of ['The event organizer chooses','People may have rights','The account service is intended','In this local preview','Šajā lokālajā priekšskatījumā','PRE-LAUNCH TEMPLATE'])assert(!privacy.includes(phrase));assert(privacy.includes('Production Supabase'));assert(privacy.includes('support@lumiq.cam'));assert(privacy.includes('neaugšupielādē īstu pasākuma viesu foto'));
 for(const [path,phrases] of [['/terms',['Working product name:','The local checkout is a simulation','Where consumer distance-contract rules apply','PRE-LAUNCH TEMPLATE']],['/refunds',['No real payment or refund','Cancellation should stop the next renewal','PRE-LAUNCH TEMPLATE','Support email: [blank]']]]){await page.goto(base+path);const text=await page.locator('main').innerText();for(const phrase of phrases)assert(!text.includes(phrase),`${path} still contains: ${phrase}`);if(path==='/terms')assert(text.includes('support@lumiq.cam'));if(path==='/refunds'){assert(text.includes('Kandidāts neapstrādā īstus maksājumus'));assert(text.includes('Atbalsta e-pasts: support@lumiq.cam'));}}
 await page.goto(base+'/security');await page.getByRole('heading',{name:'Radīts privātiem pasākumiem.',exact:true}).waitFor();assert(!(await page.locator('main').innerText()).includes('Organizers can access'));
 await page.goto(base+'/login');await page.getByRole('button',{name:'G Ienākt ar Google',exact:true}).waitFor();
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/sample-workspace');await page.locator('.desktop-workspace-nav').getByText('Mani pasākumi',{exact:true}).waitFor();const workspace=await page.locator('.workspace').innerText();for(const phrase of ['Organizer workspace','Every gathering, in one place.','Ready in four small steps.'])assert(!workspace.includes(phrase));await page.screenshot({path:'platform/test-results/workspace-lv.png',fullPage:true});
 await page.locator('.event-row').filter({hasText:'Studio evening'}).click();
 const eventPath=new URL(page.url()).pathname;
 await page.setViewportSize({width:390,height:844});const backToEvents=page.getByRole('link',{name:'Mani pasākumi',exact:true});const backBox=await backToEvents.boundingBox();assert(backBox&&backBox.height>=44,'Event list return link needs a mobile-sized touch target');await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'Drukāt vai lejupielādēt QR kodu'}).click();
  await page.locator('#qr-canvas').waitFor();assert.equal(await page.locator('#editor-text-value').count(),0,'QR text should be edited on the design, not in a separate field');assert.equal(await page.locator('#editor-align').count(),0,'QR editor should not show redundant alignment controls');
  await page.locator('#editor-draw').click();assert.equal(await page.locator('#editor-draw').getAttribute('aria-pressed'),'true');const qrCanvas=await page.locator('.qr-canvas-stage').boundingBox();await page.mouse.move(qrCanvas.x+qrCanvas.width*.3,qrCanvas.y+qrCanvas.height*.8);await page.mouse.down();await page.mouse.move(qrCanvas.x+qrCanvas.width*.36,qrCanvas.y+qrCanvas.height*.84,{steps:4});await page.mouse.up();assert.equal(await page.locator('#editor-draw').getAttribute('aria-pressed'),'false','Finishing a stroke should exit drawing mode and allow selecting layers');
  await page.locator('#editor-add-text').click();let textCanvas=await page.locator('.qr-canvas-stage').boundingBox();await page.mouse.click(textCanvas.x+textCanvas.width*.9,textCanvas.y+textCanvas.height*.9);await page.mouse.move(textCanvas.x+textCanvas.width*.23,textCanvas.y+textCanvas.height*.44);await page.mouse.down();await page.mouse.move(textCanvas.x+textCanvas.width*.29,textCanvas.y+textCanvas.height*.49,{steps:5});await page.mouse.up();await page.keyboard.type('Editable poster text');await page.locator('[data-qr-color-target="object"]').click();await page.locator('#editor-color').fill('#173e32');await page.locator('#editor-draw').click();await page.locator('#editor-add-emoji').click();assert((await page.locator('#qr-emoji-picker [data-emoji]').count())>=60);await page.locator('#qr-emoji-picker-search').fill('rose');await page.locator('#qr-emoji-picker [data-emoji]:visible').first().click();assert.equal(await page.locator('#editor-draw').getAttribute('aria-pressed'),'false','Adding an emoji should exit drawing mode');await page.locator('#editor-size').fill('96');await page.locator('#editor-undo').click();await page.locator('#editor-redo').click();await page.locator('[data-qr-color-target="background"]').click();await page.locator('#editor-color').fill('#d4b58b');await page.locator('#qr-background').setInputFiles({name:'qr-background.png',mimeType:'image/png',buffer:await sharp({create:{width:900,height:600,channels:3,background:'#d4b58b'}}).png().toBuffer()});
 const addQr=page.locator('#editor-add-qr');if(await addQr.getAttribute('aria-pressed')!=='true'){await addQr.click();await page.waitForFunction(()=>document.querySelector('#editor-add-qr')?.getAttribute('aria-pressed')==='true');}
 const qrSave=page.waitForResponse(r=>r.url().includes('/qr-layout')&&r.request().method()==='POST');await page.getByRole('button',{name:'Saglabāt dizainu'}).click();assert.equal((await qrSave).status(),200);
 await page.getByRole('button',{name:'Drukāt dizainu'}).waitFor();
  const persistedQr=await(await page.request.get(base+'/api/events/'+eventPath.match(/[0-9a-f-]{36}$/i)[0])).json();assert(persistedQr.appearance.qr_layout.scene.objects.some(o=>o.lumiqRole==='qr'&&o.src.startsWith('/api/events/')));const editableText=persistedQr.appearance.qr_layout.scene.objects.find(o=>o.text==='Editable poster text');assert(editableText&&editableText.fill==='#173e32',`Inline text editing and color should persist in the saved QR design; saved text layers: ${JSON.stringify(persistedQr.appearance.qr_layout.scene.objects.filter(o=>typeof o.text==='string').map(o=>o.text))}`);assert(Math.abs(editableText.left-1240*.08)>10||Math.abs(editableText.top-874*.42)>10,'A newly added text layer should remain selectable and movable after editing');assert(persistedQr.appearance.qr_layout.scene.objects.some(o=>o.lumiqRole==='emoji'&&o.fontSize===96),'Emoji layers should be resizable from the design tools');assert(persistedQr.appearance.qr_layout.scene.objects.some(o=>o.lumiqRole==='background'),'Uploaded/design background should be an editable scene layer');assert.equal(persistedQr.appearance.qr_layout.scene.background,'#d4b58b','Poster background color should persist with the editable scene');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Lejupielādēt dizainu'}).click();assert((await download).suggestedFilename().endsWith('.webp'));
 await page.screenshot({path:'platform/test-results/qr-builder-lv.png'});
 await page.getByRole('button',{name:'Aizvērt logu'}).click();
  await page.goto(base+eventPath+'?tab=design');await page.locator('#design-form').waitFor();
   await page.locator('#design-form [name=title]').evaluate(el=>{el.value='Vasaras vakars';el.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.locator('#guest-add-emoji').click();await page.locator('#guest-undo').click();await page.locator('#guest-redo').click();
  await page.locator('#cover-file').setInputFiles({name:'guest-cover.png',mimeType:'image/png',buffer:await sharp({create:{width:320,height:600,channels:3,background:'#397f65'}}).png().toBuffer()});
  const guestCanvas=await page.locator('#guest-canvas').boundingBox();await page.mouse.move(guestCanvas.x+guestCanvas.width*.95,guestCanvas.y+guestCanvas.height*.4);await page.mouse.down();await page.mouse.move(guestCanvas.x+guestCanvas.width+180,guestCanvas.y+guestCanvas.height*.4,{steps:8});await page.mouse.up();
  assert.equal(await page.locator('#guest-canvas').count(),1);
  const guestSave=page.waitForResponse(r=>r.url().includes('/api/events/')&&r.request().method()==='PATCH');
  await page.getByRole('button',{name:'Saglabāt viesa lapu',exact:true}).click();assert.equal((await guestSave).status(),200);
  const persisted=await(await page.request.get(base+'/api/events/'+eventPath.match(/[0-9a-f-]{36}$/i)[0])).json();
  assert.equal(persisted.appearance.title,'Vasaras vakars');assert(persisted.appearance.cover_base_key);assert(persisted.appearance.guest_design.objects.some(o=>o.lumiqRole==='guest-title'));const coverLayer=persisted.appearance.guest_design.objects.find(o=>o.lumiqRole==='background');assert(coverLayer,'Guest design should retain its cover image layer');const coverBounds={left:coverLayer.left-coverLayer.width*coverLayer.scaleX/2,top:coverLayer.top-coverLayer.height*coverLayer.scaleY/2,right:coverLayer.left+coverLayer.width*coverLayer.scaleX/2,bottom:coverLayer.top+coverLayer.height*coverLayer.scaleY/2};assert(coverBounds.left<=1&&coverBounds.top<=1&&coverBounds.right>=389&&coverBounds.bottom>=759,'Dragging the cover must never expose white space inside the guest-page bounds');assert(persisted.appearance.qr_layout.scene.objects.some(o=>o.lumiqRole==='qr'));
  await page.goto(base+eventPath+'?tab=gallery');
 const untranslated={
  design:['Guest page','Save guest page','Cover collection','Current photo','Replace photo','Button color','Welcome','Camera'],
  sharing:['Guests use the same event link','Photo and gallery requests','Up to 60 days'],
  settings:['Photos remain available until','Archiving does not extend','Move it out of your main event list','Access is removed immediately'],
  billing:['Current period ends','Published events keep','A draft is free to prepare'],
  account:['Request a review of your account'],
  admin:['Local service health','Accounts','Failed jobs','Open cases','Audit entries','Support cases','Background jobs','Recent service emails','Usage measurements','Audit trail','Attempt 0']
 };
 for(const tab of ['design','sharing','settings']){
  await page.goto(base+eventPath+`?tab=${tab}`);await page.locator('main').waitFor();const content=await page.locator('main').innerText();for(const phrase of untranslated[tab])assert(!content.includes(phrase),`${tab} still contains: ${phrase}`);
 }
 for(const section of ['billing','account','admin']){
  await page.goto(base+`/app/${section}`);await page.locator('main').waitFor();const content=await page.locator('main').innerText();for(const phrase of untranslated[section])assert(!content.includes(phrase),`${section} still contains: ${phrase}`);
 }
 const covers=['garden-gathering','wedding-toast','party','coastal-celebration','city-rooftop'];for(const c of covers){const r=await page.request.get(base+'/assets/'+c+'.webp');assert(r.ok());assert((await sharp(await r.body()).metadata()).width>300);}
 assert.deepEqual(errors,[]);console.log('Refinement browser passed: aligned pricing, fixed viewer, backdrop, swipe and five bundled covers.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
