import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto';
import {uuid,token,hash,email,text,requireThat,cookies,confirmedPassword} from './security.mjs';
import {profileDetails} from './profile.mjs';
export function supabaseAuthService(db,{origin,mail,fetcher=fetch,sessionRpc=db.sessionRpc||null}){
 const url=process.env.PLATFORM_SUPABASE_URL,key=process.env.PLATFORM_SUPABASE_PUBLISHABLE_KEY;
 requireThat(url&&key&&!url.includes('ojcvnsbhphvijmzjfenl'),503,'Configure a new isolated Supabase Auth project.');
 const secret=Buffer.from(process.env.PLATFORM_SESSION_ENCRYPTION_KEY||'','hex');requireThat(secret.length===32,503,'Configure the server session-encryption secret.');
 const accessByUser=new WeakMap();
 const seal=data=>{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',secret,iv);const body=Buffer.concat([cipher.update(Buffer.from(JSON.stringify(data),'utf8')),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64');};
 const open=data=>{const bytes=Buffer.from(data,'base64'),cipher=createDecipheriv('aes-256-gcm',secret,bytes.subarray(0,12));cipher.setAuthTag(bytes.subarray(12,28));return JSON.parse(Buffer.concat([cipher.update(bytes.subarray(28)),cipher.final()]).toString());};
 const request=async(route,body,access,method=body?'POST':'GET')=>{const r=await fetcher(`${url}/auth/v1/${route}`,{method,headers:{apikey:key,'Content-Type':'application/json',...(access?{Authorization:`Bearer ${access}`}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(20000)});let data={};try{data=await r.json();}catch{}requireThat(r.ok,r.status===429?429:400,r.status===429?'Too many attempts. Please wait.':'Authentication could not be completed. Check your details or request a new email link.');return data;};
 const rpc=async(name,args,access)=>{const result=await fetcher(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:key,...(access?{Authorization:`Bearer ${access}`}:{ }),'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(20000)});let data;try{data=await result.json();}catch{}requireThat(result.ok,403,'The account could not be synchronized. Please sign in again.');return data;};
 const sessionCall=(name,args,access)=>sessionRpc?sessionRpc(name,args,access):rpc(name,args,access);
 const sync=async(user,access)=>{requireThat(user?.id&&user.email_confirmed_at&&access,403,'Verify your email before signing in.');const metadata=user.user_metadata||{},profile=metadata.profile&&typeof metadata.profile==='object'&&!Array.isArray(metadata.profile)?metadata.profile:{},result=await rpc('sync_own_account',{p_name:String(metadata.name||metadata.full_name||'Organizer').slice(0,80),p_profile:profile,p_locale:metadata.locale==='lv'?'lv':'en',p_marketing:metadata.marketing===true},access),account=Array.isArray(result)?result[0]:result;requireThat(account?.account_id===user.id,403,'This account is no longer available. Contact support.');const safe={id:account.account_id,email:account.email,name:account.name,role:account.role,preferences:account.preferences,profile:account.profile,design_defaults:account.design_defaults};accessByUser.set(safe,access);return safe;};
 const storeSession=async(user,sessionToken,providerSession)=>{const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');requireThat(await sessionCall('create_own_app_session',{p_hash:hash(sessionToken),p_provider_session:seal(providerSession)},access)===true,403,'Could not create a secure session.');};
 const revokeOwnSessions=async(user)=>{const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return sessionCall('delete_own_app_sessions',{},access);};
 const fresh=async req=>{
  const cookie=cookies(req.headers.get('cookie')).lumiq_session;if(!cookie)return null;
  const tokenHash=hash(cookie),row=await sessionCall('get_app_session',{p_hash:tokenHash});if(!row?.provider_session)return null;
  let session;try{session=open(row.provider_session);}catch{await sessionCall('delete_app_session',{p_hash:tokenHash});return null;}
  if(session.expires_at*1000<Date.now()+30000){
   try{session=await request('token?grant_type=refresh_token',{refresh_token:session.refresh_token});requireThat(await sessionCall('update_app_session',{p_hash:tokenHash,p_provider_session:seal(session)})===true,401,'Sign in again to continue.');}
   catch{await sessionCall('delete_app_session',{p_hash:tokenHash});return null;}
  }
  return{row:{token_hash:tokenHash,account_id:row.account_id},session};
 };
 return{mail,
  async listEvents(user){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('list_own_events',{},access);return Array.isArray(result)?result:[];},
  async getEvent(user,eventId){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('get_own_event',{p_event_id:eventId},access);return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async getBilling(user){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('get_own_billing',{},access);return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async createOwnOrder(user,orderId,plan){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('create_own_order',{p_order_id:orderId,p_plan:plan},access);},
  async setOwnOrderProvider(user,orderId,providerId){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('set_own_order_provider',{p_order_id:orderId,p_provider_id:providerId},access);},
  async cancelOwnSubscription(user){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('cancel_own_subscription',{},access);},
  async getOwnSubscriptionPaymentDetails(user){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('get_own_subscription_payment_details',{},access);},
  async getAdminDashboard(user){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('get_admin_dashboard',{},access);},
  async recordAdminBillingReconcile(user,providerId){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('record_admin_billing_reconcile',{p_provider_id:providerId},access);},
  async retryAdminDelivery(user,id){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('retry_admin_delivery',{p_id:id},access);},
  async replyAdminSupport(user,id,reply){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('reply_admin_support',{p_id:id,p_reply:reply},access);},
  async retryAdminJob(user,id){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('retry_admin_job',{p_id:id},access);},
  async createSupportCase(user,{email,subject,message}){const access=user?accessByUser.get(user):null;if(user)requireThat(access,401,'Sign in to continue.');return rpc('create_support_case',{p_email:email,p_subject:subject,p_message:message},access);},
  async listOwnSupportCases(user){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('list_own_support_cases',{},access);return Array.isArray(result)?result:[];},
  async consumeRequestLimit(keyHash,windowId,limit){const count=await rpc('consume_request_limit',{p_key_hash:keyHash,p_window_id:windowId,p_limit:limit});requireThat(Number.isInteger(count)&&count>=1,503,'Request limits could not be checked.');return count;},
  async createEvent(user,event){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('create_own_event',{p_event_id:event.id,p_slug:event.slug,p_name:event.name,p_description:event.description,p_starts_at:event.starts_at,p_ends_at:event.ends_at,p_time_zone:event.time_zone,p_appearance:event.appearance},access);const created=result&&typeof result==='object'&&!Array.isArray(result)?result:null;requireThat(created?.id===event.id&&created.owner_id===user.id,403,'The event could not be created for this account.');return created;},
  async createEventPreview(user,eventId,tokenHash){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('create_own_event_preview',{p_event_id:eventId,p_token_hash:tokenHash},access);},
  async getEventPreview(slug,tokenHash){return rpc('get_event_preview',{p_slug:slug,p_token_hash:tokenHash});},
  async updateEvent(user,event){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('update_own_event',{p_event_id:event.id,p_name:event.name,p_description:event.description,p_starts_at:event.starts_at,p_ends_at:event.ends_at,p_time_zone:event.time_zone,p_appearance:event.appearance,p_use_preset:event.usePreset},access);const updated=result&&typeof result==='object'&&!Array.isArray(result)?result:null;requireThat(updated?.id===event.id&&updated.owner_id===user.id,403,'The event could not be updated for this account.');return updated;},
  async eventAction(user,eventId,input){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('act_on_own_event',{p_event_id:eventId,p_action:input.action,p_funding:input.funding||'plan',p_confirm:input.confirm??null,p_enabled:input.enabled??null,p_days:input.days??null},access);return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async saveQrLayout(user,eventId,layout){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('save_own_qr_layout',{p_event_id:eventId,p_layout:layout},access);return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async reserveDesignAsset(user,eventId,assetType){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('reserve_own_design_asset',{p_event_id:eventId,p_asset_type:assetType},access);requireThat(typeof result?.reservation_id==='string'&&typeof result?.object_key==='string',403,'The design upload could not be reserved.');return{reservationId:result.reservation_id,key:result.object_key};},
  async attachDesignAsset(user,eventId,assetType,key,reservationId){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('attach_own_design_asset',{p_event_id:eventId,p_asset_type:assetType,p_object_key:key,p_reservation_id:reservationId},access);requireThat(result?.ok===true,403,'The design upload could not be attached.');return result;},
  async getCoverAsset(user,eventId,{camera=false,source=false}={}){const access=user?accessByUser.get(user):null;if(user)requireThat(access,401,'Sign in to continue.');const result=await rpc('get_event_cover_asset',{p_event_id:eventId,p_camera:camera,p_source:source},access);return typeof result==='string'?result:null;},
  async joinPublicEvent(eventId,{id,name,tokenHash}){const result=await rpc('join_public_event',{p_event_id:eventId,p_guest_id:id,p_name:name,p_token_hash:tokenHash});return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async getPublicGuestIdentity(eventId,tokenHash){const result=await rpc('get_public_guest_identity',{p_event_id:eventId,p_token_hash:tokenHash});return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async getPublicEvent(slug){const result=await rpc('get_public_event',{p_slug:slug});return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async consumePublicGalleryShare(eventId){const result=await rpc('consume_public_gallery_share',{p_event_id:eventId});requireThat(result?.ok===true,403,'This gallery is not shared or its viewing allowance has ended.');return result;},
  async listOwnGallery(user,eventId,query){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');return rpc('list_own_gallery',{p_event_id:eventId,p_guest:query.guest,p_date:query.date,p_time_zone:query.timeZone,p_oldest:query.oldest,p_cursor_created:query.cursorCreated,p_cursor_id:query.cursorId},access);},
  async listPublicGallery(eventId,query){return rpc('list_public_gallery',{p_event_id:eventId,p_guest:query.guest,p_date:query.date,p_time_zone:query.timeZone,p_oldest:query.oldest,p_cursor_created:query.cursorCreated,p_cursor_id:query.cursorId});},
  async getOwnPhotoAsset(user,photoId,thumbnail){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('get_own_photo_asset',{p_photo_id:photoId,p_thumbnail:thumbnail},access);return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async getPublicPhotoAsset(photoId,thumbnail){const result=await rpc('get_public_photo_asset',{p_photo_id:photoId,p_thumbnail:thumbnail});return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async curateOwnGallery(user,eventId,photoIds,action){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('curate_own_gallery',{p_event_id:eventId,p_photo_ids:photoIds,p_action:action},access);requireThat(result?.ok===true,403,'The gallery could not be updated.');return result;},
  async listOwnExports(user,eventId){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('list_own_event_exports',{p_event_id:eventId},access);return Array.isArray(result)?result:[];},
  async getOwnExportJob(user,jobId){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('get_own_export_job',{p_job_id:jobId},access);return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async getOwnExportPart(user,jobId,partIndex){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('get_own_export_part',{p_job_id:jobId,p_part_index:partIndex},access);return result&&typeof result==='object'&&!Array.isArray(result)?result:null;},
  async retryOwnExport(user,jobId){const access=accessByUser.get(user);requireThat(access,401,'Sign in to continue.');const result=await rpc('retry_own_export',{p_job_id:jobId},access);requireThat(result?.ok===true,404,'Job not available for retry.');return result;},
  async claimPlatformJob(jobIds){return(await db.query('select public.claim_platform_job($1::uuid[]) as job',[jobIds])).rows[0].job;},
  async claimPlatformQueueBatch(limit){const result=(await db.query('select public.claim_platform_queue_batch($1::integer) as ids',[limit])).rows[0].ids;return Array.isArray(result)?result:[];},
  async resetPlatformQueueDispatch(ids){return(await db.query('select public.reset_platform_queue_dispatch($1::uuid[]) as count',[ids])).rows[0].count;},
  async recoverStalePlatformJobs(){return(await db.query('select public.recover_stale_platform_jobs() as count')).rows[0].count;},
  async getPlatformCleanupManifest(id){return(await db.query('select public.get_platform_cleanup_manifest($1::uuid) as manifest',[id])).rows[0].manifest;},
  async canDeletePlatformAsset(id,key){return(await db.query('select public.can_delete_platform_asset($1::uuid,$2::text) as allowed',[id,key])).rows[0].allowed;},
  async savePlatformThumbnailDetails(jobId,photoId,bytes,checksum){return(await db.query('select public.save_platform_thumbnail_details($1::uuid,$2::uuid,$3::integer,$4::text) as saved',[jobId,photoId,bytes,checksum])).rows[0].saved;},
  async platformMediaCleanupShouldDefer(id){return(await db.query('select public.platform_media_cleanup_should_defer($1::uuid) as should_defer',[id])).rows[0].should_defer;},
  async finalizePlatformEventCleanup(id,removed){return(await db.query('select public.finalize_platform_event_cleanup($1::uuid,$2::integer) as result',[id,removed])).rows[0].result;},
  async preparePlatformEventEnd(id){return(await db.query('select public.prepare_platform_event_end($1::uuid) as result',[id])).rows[0].result;},
  async expirePlatformEvent(id){return(await db.query('select public.expire_platform_event($1::uuid) as result',[id])).rows[0].result;},
  async runPlatformRetentionCycle(limit=250){return(await db.query('select public.run_platform_retention_cycle($1::integer) as result',[limit])).rows[0].result;},
  async listPlatformRetentionReminders(limit=250){const result=(await db.query('select public.list_platform_retention_reminders($1::integer) as reminders',[limit])).rows[0].reminders;return Array.isArray(result)?result:[];},
  async collectPlatformNotices(){return(await db.query('select public.collect_platform_notices() as count')).rows[0].count;},
  async renewPlatformJob(id){return(await db.query('select public.renew_platform_job($1::uuid) as renewed',[id])).rows[0].renewed;},
  async settlePlatformJob(id,outcome,{result=null,error=null,delaySeconds=0,decrementAttempt=false}={}){return(await db.query('select public.settle_platform_job($1::uuid,$2::text,$3::jsonb,$4::text,$5::integer,$6::boolean) as result',[id,outcome,result,error,delaySeconds,decrementAttempt])).rows[0].result;},
  async deadLetterPlatformJob(id){return(await db.query('select public.dead_letter_platform_job($1::uuid) as job',[id])).rows[0].job;},
  async preparePlatformExport(id){return(await db.query('select public.prepare_platform_export($1::uuid) as result',[id])).rows[0].result;},
  async getPlatformExportPart(id){const result=(await db.query('select public.get_platform_export_part($1::uuid) as items',[id])).rows[0].items;return Array.isArray(result)?result:[];},
  async completePlatformExportPart(id,result){return(await db.query('select public.complete_platform_export_part($1::uuid,$2::jsonb) as parent',[id,result])).rows[0].parent;},
  async getPlatformExportNotice(ownerId){return(await db.query('select public.get_platform_export_notice($1::uuid) as notice',[ownerId])).rows[0].notice;},
  async reserveGuestPhoto({eventId,photoId,guestId,guestTokenHash,guestFolder,filenamePrefix,name,bytes,thumbnailBytes,checksum,thumbnailChecksum,capturedAtMs}){const result=await rpc('reserve_guest_photo',{p_event_id:eventId,p_photo_id:photoId,p_guest_token_hash:guestTokenHash,p_guest_folder:guestFolder,p_filename_prefix:filenamePrefix,p_name:name,p_bytes:bytes,p_thumbnail_bytes:thumbnailBytes,p_checksum:checksum,p_thumbnail_checksum:thumbnailChecksum,p_captured_at_ms:capturedAtMs});requireThat(result?.id===photoId&&result?.guest_id===guestId&&result?.status,403,'Could not reserve this photo.');return result;},
  async getGuestPhotoUpload(eventId,photoId,tokenHash){return rpc('get_guest_photo_upload',{p_event_id:eventId,p_photo_id:photoId,p_token_hash:tokenHash});},
  async finalizeGuestPhoto(eventId,photoId,tokenHash){const result=await rpc('finalize_guest_photo',{p_event_id:eventId,p_photo_id:photoId,p_token_hash:tokenHash});requireThat(result?.ok===true,403,'The photo could not be finalized.');return result;},
  async discardGuestPhoto(eventId,photoId,tokenHash){const result=await rpc('discard_guest_photo',{p_event_id:eventId,p_photo_id:photoId,p_token_hash:tokenHash});requireThat(result?.ok===true,403,'The photo could not be discarded.');return result;},
  googleStart(){
   const state=token(),verifier=randomBytes(48).toString('base64url'),challenge=createHash('sha256').update(verifier).digest('base64url');
   const redirect=`${origin}/api/auth/google/callback`,authorize=new URL(`${url}/auth/v1/authorize`);
   authorize.search=new URLSearchParams({provider:'google',redirect_to:redirect,code_challenge:challenge,code_challenge_method:'s256',state}).toString();
   return{url:authorize.toString(),cookie:`lumiq_oauth=${encodeURIComponent(seal({state,verifier,expires:Date.now()+600000}))}; Path=/api/auth/google; HttpOnly; SameSite=Lax; Secure; Max-Age=600`};
  },
  async googleCallback(req,callback){
   const value=cookies(req.headers.get('cookie')).lumiq_oauth;requireThat(value,400,'This Google sign-in request has expired. Start again.');
   let pending;try{pending=open(decodeURIComponent(value));}catch{throw Object.assign(new Error('This Google sign-in request is invalid. Start again.'),{status:400});}
   requireThat(pending.expires>Date.now()&&callback.searchParams.get('state')===pending.state,400,'This Google sign-in request is invalid. Start again.');
   const code=callback.searchParams.get('code');requireThat(code,400,'Google sign-in was canceled or could not be completed.');
   const result=await request('token?grant_type=pkce',{auth_code:code,code_verifier:pending.verifier});
   const user=await sync(result.user,result.access_token),sessionToken=token();await storeSession(user,sessionToken,result);
   return{cookie:`lumiq_session=${sessionToken}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=604800`,clear:'lumiq_oauth=; Path=/api/auth/google; HttpOnly; SameSite=Lax; Secure; Max-Age=0'};
  },
  async user(req){const context=await fresh(req);if(!context)return null;try{return await sync(await request('user',null,context.session.access_token),context.session.access_token);}catch{return null;}},
  async register(input){requireThat(typeof input.password==='string'&&input.password.length>=12&&input.password.length<=128,400,'Use a password with 12 to 128 characters.');const details=profileDetails(input);await request(`signup?redirect_to=${encodeURIComponent(origin+'/auth/verify')}`,{email:email(input.email),password:input.password,data:{name:details.name,profile:details.profile,locale:input.locale==='lv'?'lv':'en'}});return{message:'Check your email to verify your account.'};},
  async login(input){const result=await request('token?grant_type=password',{email:email(input.email),password:input.password});const user=await sync(result.user,result.access_token),t=token();await storeSession(user,t,result);return{user:{id:user.id,email:user.email,name:user.name,role:user.role},cookie:`lumiq_session=${t}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=604800`};},
  async logout(req){const c=await fresh(req);if(c){await request('logout',{},c.session.access_token).catch(()=>{});await sessionCall('delete_app_session',{p_hash:c.row.token_hash});}},
  async requestReset(input){await request(`recover?redirect_to=${encodeURIComponent(origin+'/auth/reset')}`,{email:email(input.email)});return{message:'If the account exists, a reset email is on its way.'};},
  async consume(input){
   const resetPassword=input.purpose==='reset'?confirmedPassword(input):null;
   if(input.access_token&&input.purpose==='verify'&&input.type==='signup'){requireThat(typeof input.refresh_token==='string',400,'This confirmation link is invalid. Request a new one.');const providerSession={access_token:text(input.access_token,8192),refresh_token:text(input.refresh_token,8192),expires_at:Math.floor(Date.now()/1000)+Math.min(86400,Math.max(60,Number(input.expires_in)||3600))};const user=await request('user',null,providerSession.access_token);const account=await sync(user,providerSession.access_token),sessionToken=token();await storeSession(account,sessionToken,providerSession);return{message:'Email confirmed. Your account is ready.',cookie:`lumiq_session=${sessionToken}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=604800`};
   }
   if(input.access_token&&input.purpose==='reset'&&input.type==='recovery'){
    const access=text(input.access_token,8192),user=await request('user',null,access),account=await sync(user,access);await request('user',{password:resetPassword},access,'PUT');await revokeOwnSessions(account);return{message:'Your password has been updated. Sign in to continue.'};
   }
   if(input.access_token&&input.purpose==='email'&&input.type==='email_change'){
    const access=text(input.access_token,8192),user=await request('user',null,access),account=await sync(user,access);await revokeOwnSessions(account);return{message:'Your account email has been updated. Sign in to continue.'};
   }
   requireThat(!input.access_token,400,'This confirmation link is invalid. Request a new one.');
   const purpose=input.purpose==='reset'?'recovery':input.purpose==='email'?'email_change':'email',password=purpose==='recovery'?(resetPassword||confirmedPassword(input)):null;const session=await request('verify',{token_hash:text(input.token,256),type:purpose});if(purpose==='recovery')await request('user',{password},session.access_token,'PUT');const account=await sync(session.user,session.access_token);await revokeOwnSessions(account);return{message:'Your account has been updated. Sign in to continue.'};
  },
  async revokeOwnAppSessions(user){return revokeOwnSessions(user);},
  async update(user,input){const details=profileDetails(input,user.profile||{}),session=await request('token?grant_type=password',{email:user.email,password:input.password});requireThat(session.user.id===user.id,403,'Account mismatch.');const target=input.email!==user.email?`user?redirect_to=${encodeURIComponent(origin+'/auth/email')}`:'user',preferences={service:true,marketing:input.marketing===true,locale:input.locale==='lv'?'lv':'en'};const updated=await request(target,{data:{name:details.name,profile:details.profile,locale:preferences.locale,marketing:preferences.marketing},...(input.email!==user.email?{email:email(input.email)}:{})},session.access_token,'PUT');await sync(updated,session.access_token);return{message:'Profile saved. Check the confirmation email if you changed your address.'};},
 };
}
